export default function OurImpact() {
    return (
        <div className="min-h-screen bg-purple-950 text-white flex flex-col items-center justify-center p-8">
            <h1 className="text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-orange-400 mb-6">Our Impact</h1>
            <p className="text-xl text-purple-200 max-w-2xl text-center">
                See the economic and creative footprint generated by the millions of collabs happening on our platform.
            </p>
        </div>
    );
}
